// LOOKING GLASS service worker (3c.6, HF24 #1): offline play + instant repeat loads. Generated by build.mjs from src/sw.template.js.
// build: "Drop 3d.3 · Evacuating Americans (NEO) · 2026-09-28 07:03 KST"
const CACHE = "lg-ab8ea4b608", RUNTIME = "lg-runtime-v1", PRECACHE = ["./","app-be88c9ac96.js","media/data-073f97c4f3.js","world-data.json","icons/icon-192.png","icons/icon-512.png","icons/maskable-192.png","icons/apple-touch-icon.png","icons/favicon-64.png","media/map_relief_2k.webp","media/map_clouds.webp","media/map_glint.webp","media/intros.json","media/storylines.json","media/storylines2.json","media/a/intro_bombers-IEFBK6RK.webp","media/a/intro_capitol-UMM7OBDZ.webp","media/a/intro_carrier-5OZ7ZNPB.webp","media/a/intro_command-7IZBHLY6.webp","media/a/intro_joint-SDSJ3YJW.webp","media/a/intro_launch-ZL3AGDTA.webp","media/a/intro_missiles-2X2AOPHA.webp","media/a/intro_sign-U4S56X3Z.webp","media/a/pres_oval-3D7LIDMR.jpg","media/a/pres_podium_seal-A4S7UZNY.jpg","media/a/pres_seal_sm-XTB24VRQ.webp"];
self.addEventListener("install", (e) => {
  // 3c.6.1: install can never fail. Files are cached one by one; a missing/slow file is skipped (cached later on use).
  e.waitUntil((async () => {
    try {
      const c = await caches.open(CACHE);
      // hashed files never change, so the copy the page just downloaded (HTTP cache) is reused instead of fetched twice
      await Promise.all(PRECACHE.map(async (u) => { try { const r = await fetch(new Request(u, { cache: /-[0-9a-zA-Z]{8,10}\.(js|webp|jpg|png)$/.test(u) ? "default" : "reload" })); if (r && r.ok) await c.put(u, r); } catch (err) {} }));
    } catch (err) {}
    self.skipWaiting();
  })());
});
self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k !== CACHE && k !== RUNTIME) await caches.delete(k);
    await self.clients.claim();
  })());
});
const timeout = (ms) => new Promise((res) => setTimeout(() => res(null), ms)); // resolves null = too slow (no stray rejections)
async function fromCache(req, ...alts) {
  for (const r of [req, ...alts]) { const hit = await caches.match(r, { ignoreSearch: typeof r === "string" }); if (hit) return hit; }
  return null;
}
self.addEventListener("fetch", (e) => {
  const req = e.request, url = new URL(req.url);
  if (req.method !== "GET" || url.origin !== location.origin) return;           // live weather / news APIs go straight to the network
  if (req.headers.has("range") || /\.mp4$/.test(url.pathname)) return;          // intro videos stream from the network (too big to cache)
  if (/version\.json$|\.webmanifest$|\/sw\.js$/.test(url.pathname)) return; // update checks + install metadata always see the network
  if (req.mode === "navigate") {                                                // the page: network first (so updates land), cache when offline/slow
    e.respondWith((async () => {
      try {
        const r = await Promise.race([fetch(req), timeout(4000)]);
        if (!r) throw new Error("slow");
        if (r.ok) { const c = await caches.open(CACHE); c.put("./", r.clone()); }
        return r;
      } catch { return (await fromCache("./")) || new Response("<h1>Offline</h1><p>Open LOOKING GLASS once online to install it.</p>", { headers: { "content-type": "text/html" } }); }
    })());
    return;
  }
  if (/\.json$/.test(url.pathname)) {                                           // data files (live world data, intro list, storylines): network first, last good copy offline
    const key = url.origin + url.pathname;                                        // (cache-busting ?cb= queries share one entry)
    e.respondWith((async () => {
      try { const r = await Promise.race([fetch(req), timeout(6000)]); if (!r) throw new Error("slow"); if (r.ok) (await caches.open(RUNTIME)).put(key, r.clone()); return r; }
      catch { return (await caches.match(key, { ignoreSearch: true })) || Response.error(); }
    })());
    return;
  }
  e.respondWith((async () => {                                                  // everything else (hashed images, map layers, voice, 3D bundle): cache first
    const hit = await caches.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try {
      const r = await fetch(req);
      if (r.ok && r.type === "basic") (await caches.open(RUNTIME)).put(url.origin + url.pathname, r.clone());
      return r;
    } catch { return Response.error(); }
  })());
});
self.addEventListener("message", (e) => { if (e.data === "lg-status") caches.keys().then((k) => e.source && e.source.postMessage({ lg: "sw", caches: k, cache: CACHE })); });
